### ISSUE TITLE
How to change username and email from git

### ISSUE THREAD

**Issue by angeloreis** [samara-maia/-Full-Stack-Development-QA#1]
`Aulas da automação Expert | Full Stack da instituição {Prças}
estou fazendo no Notboock que pertece a Angelo Reis, por isso o nome dele em alguns commits,
até o retorno do meu que está em manutenção.`

Open terminal and enter folder project...

`git config --global user.name samara-maia && git config --global user.email <PUT_YOUR_EMAIL_HERE>`

Done!

**Comment by samara-maia** [comment]
solved
